{% set name = "pycognito" %}
{% set version = "2022.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b182576be28e0c71d4a12b91fdb4efb00e5a9a7a43dee9aef7dd52ab8efd084

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - boto3 >=1.10.49
    - envs >=1.3
    - python >={{ python_min }}
    - python-jose >=3.2.0
    - requests >=2.22.0

test:
  imports:
    - pycognito
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pvizeli/pycognito
  license: Apache-2.0
  license_file: LICENSE
  summary: Python class to integrate Boto3's Cognito client so it is easy to login users. With SRP support.
  doc_url: https://github.com/pvizeli/pycognito/blob/master/README.md
  dev_url: https://github.com/pvizeli/pycognito

extra:
  recipe-maintainers:
    - kellpossible
